server:
  port: 8080
  servlet: 
    context-path: /nfdw-admin
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    druid:
      url: jdbc:mysql://172.31.50.45:3306/guangzhou?useUnicode=true&characterEncoding=UTF-8	  
      username: root
      password: nfdw123456
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvi2ctableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: \*\.js, \*\.gif, \*\.jpg, \*\.png, \*\.css,  \*\.ico, /druid/\*
        session-stat-enable: true
        session-stat-max-count: 1000
        principal-session-name: curentUser.username
        profile-enable: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
      aop-patterns: com.nfdw.service.impl.*
      
  http:
    encoding:
      force: true
  boot:
    admin:
      client:
        prefer-ip: true
      url: http://localhost:8082
  freemarker: 
    allow-session-override: true

mybatis:
  type-aliases-package: com.nfdw.entity
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  configuration: 
    cache-enabled: false 
    aggressive-lazy-loading: false 
    multiple-result-sets-enabled: true 
    map-underscore-to-camel-case: true 
    use-generated-keys: true 
    default-executor-type: BATCH 
    default-statement-timeout: 600 
    log-impl: org.apache.ibatis.logging.log4j.Log4jImpl
mapper:
  mappers:
    - com.nfdw.base.BaseMapper
    - tk.mybatis.mapper.common.Mapper
  not-empty: true
  identity: mysql


# PageHelperConfig 可以替代此方案
pagehelper:
  helperDialect: mysql
  offsetAsPageNum: true 
  rowBoundsWithCount: true
  pageSizeZero: true 
  reasonable: false 
  supportMethodsArguments: true
  params: count=countSql

lenosp:
  uploadPath: ./file/
  isDayType: false

  imagePath: ./image/

logging:
  file: ./logs/nfdw-log.log
  level:
    com.nfdw.mapper: debug

dataType: mysql

nfdw: 
  card: 
    getCarInfo: 
      url: http://172.31.50.43:8080/guizhouPowercon/service/devicesUsed.do
    startOrShutCard: 
      url: http://172.31.50.43:8080/guizhouPowercon/service/devicesEdit.do
  terminal: 
    # 设备升级
    deviceUpdate: 
      url: http://172.31.50.23:8081/scheduleTaskSys/updatedrivice
    # 设备重启
    deviceReboot: 
      url: http://172.31.50.23:8081/scheduleTaskSys/drivicereboot
    # 设备采集
    collect: 
      url: http://172.31.50.23:8081/scheduleTaskSys/autoselect
    # 设备采集
    infosetInterface: 
      url: http://172.31.50.23:8081/scheduleTaskSys/preset
  equipment: 
    startUpDetection: 
      url: http://172.31.50.23:8081/scheduleTaskSys/deviceNetDetection
      